name: Build and deploy container app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Get version tag
      id: get_commit_tag
      run: |
        # Extract the first word of the commit message
        FIRST_WORD=$(git log -1 --pretty=format:'%s' | awk '{print $1}')
        echo "commit_tag=$FIRST_WORD" >> $GITHUB_ENV

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          gabcat/next-try:latest
          gabcat/next-try:${{ env.commit_tag }}  
        file: ./Dockerfile
